import Link from "next/link";
import "./globals.css";
import LoginBtn from "./LoginBtn";
import { getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  //로그인된 유저정보 출력(getServerSession)
  let session = await getServerSession(authOptions);
  console.log(session);

  return (
    <html lang="en">
      <body>
        <div className="navbar">
          <Link href="/" className="logo">
            Appleforum
          </Link>
          <Link href="/list">List</Link>
          <Link href="/write">Write</Link>
          {session ? null : <Link href="/register">횐가입</Link>}
          <LoginBtn session={session} />
        </div>
        {children}
      </body>
    </html>
  );
}
